// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD415NXUn7-0bDvEXw-NGv2OemsU7js6M8',
    appId: '1:1031927211632:android:204cc252c1db537ba4f6b5',
    messagingSenderId: '1031927211632',
    projectId: 'helfer-b1d14',
    storageBucket: 'helfer-b1d14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU3_K4ZSSkacxLGEwKimrfkiozEEgD8KA',
    appId: '1:1031927211632:ios:bf6b87f18dc0b55fa4f6b5',
    messagingSenderId: '1031927211632',
    projectId: 'helfer-b1d14',
    storageBucket: 'helfer-b1d14.firebasestorage.app',
    iosBundleId: 'com.example.helfer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBG7-oh8Fy_f7p5qD4QKHIeEugBR_tapQ',
    appId: '1:219403253505:ios:071d87fc0cc39b6c5c0d00',
    messagingSenderId: '219403253505',
    projectId: 'pharma-d07ac',
    storageBucket: 'pharma-d07ac.firebasestorage.app',
    androidClientId: '219403253505-crg3r2859ht45ahp6fm939or0nhatjhj.apps.googleusercontent.com',
    iosClientId: '219403253505-v0csi3subdvq3q147jjs819i2om3nima.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharma',
  );

}